src/config/routes.rb
=begin 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: routes.rb
#Description: This file helps define paths by telling the 
rails server how incoming requests are sent to which controller and method
#Last modified on: 03-24-2022
=end 

# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :surveys
  resources :helpquizzes
  resources :lawquizzes
  resources :statsquizzes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller' 

  #added two routes
  root 'home#index'
  get 'home/DV'
  get 'home/testimonies'
  get 'home/resources'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the home page already made for you
class HomeController < ApplicationController
  # No sign in needed to access these pages
  # Overrides ApplicationController's instructions to check for login by default
  skip_before_action :authenticate_user!

  # GET /
  #
  # This method is empty, yet it works?
  # Rails controller methods can be completely empty and work just fine.
  # It's the name of the method matching to a html.erb file that
  # makes the link between the files.
  # Find me @ app/views/home/index.html.erb
  #
  # Also, any local variable made inside this method will also exist
  # in the view to be displayed. Do not look up information within the
  # view itself. Do it here, please!
  def index; end
  def DV; end
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods accessable for views within the home folder
module HomeHelper
end

src/app/views/home/DV.html.erb
<!-- 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: DV.html.erb
#Description: This is an html page that contains information on the learn more nav bar page. 
#Last modified on: 04-25-2022 */-->

<head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=
        "width=device-width, initial-scale=1, 
        shrink-to-fit=no">
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  
    <title>Bootstrap 4 Shadow</title>
</head>

<!-- To use custom fonts -->
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">

<!--formatting and information for the text to provide hover effects-->
<section class="news pt-0 bg-white">
  <div class="image-block-inner">
  <div class="card mt-md-5 my-5 shadow-lg p-3 mb-5 rounded", style="background-color: #301934"> 
    <div class="row ">
    <div class="text-center col-md-8 mx-auto"> 
    <hr class="divider border border-5"/>
    <h2 class="mx-4 my-0 text-center text-white">Let's Learn About Domestic Violence</h2> 
    <hr class="divider border border-5"/> 
    </div></div>
    <ul class="row d-lg-flex list-unstyled image-block justify-content-center px-lg-0 mx-lg-0">
      <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white ">
          <a class="mh-100 text-dark" href= <%= home_testimonies_path %> >
          <span class="hp-posts-cat">Real Life Stories</span> 
          <hr class="divider border border-5"/>  
          <h4><%= link_to 'First Hand Testimonies and victim stories', home_testimonies_path, class:"mt-3 text-dark" %> 
          </h4>
        </div> <!-- end of box outline -->
      </li>
      <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white">
          <a class="mh-100 text-dark" href=<%= lawquizzes_path %>>
          <span class="hp-posts-cat">Learn about laws</span> 
          <hr class="divider border border-5"/> 
          <h4 class="mt-3"><a class= "text-dark" href=<%= lawquizzes_path %>>Find out more about the laws and regulations regarding Domestic Violence</a></h4>
          <a href=<%= new_lawquiz_path%> class="read-more text-dark">Click Here to take Quiz</a>
        </div> <!-- end of box outline -->
      </li>
      <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white ">
          <a class="mh-110 text-dark" href=<%= statsquizzes_path %>> 
          <span class="hp-posts-cat">Statistics & Facts</span>
          <hr class="divider border border-5"/> 
          <h4 class="mt-3"><a class= "text-dark" href=<%= statsquizzes_path %>>Learn about Statistics and Facts regarding Domestic Violence</a></h4>
          <a href=<%=new_statsquiz_path%> class="read-more text-dark">Click Here to take Quiz</a>
        </div> <!-- end of box outline -->
      </li> 
      <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white ">
          <a class="mh-110 text-dark" href=<%= helpquizzes_path%>>
          <span class="hp-posts-cat">How Can You Help? </span>
          <hr class="divider border border-5"/> 
          <h4 class="mt-3"><a class= "text-dark" href=<%= helpquizzes_path %>>Learn about Statistics and Facts regarding Domestic Violence</a></h4>
          <a href=<%=new_helpquiz_path%> class="read-more text-dark">Click Here to take Quiz</a>
        </div> <!-- end of box outline -->
      </li> 
            <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white ">
          <a class="mh-110 text-dark" href=<%= home_resources_path %>>
          <span class="hp-posts-cat">Links Used &  Helpful Resources</span>
          <hr class="divider border border-5"/> 
          <h4 class="mt-3"><a class= "text-dark" href=<%= home_resources_path %>>Learn about Statistics and Facts regarding Domestic Violence</a></h4>
        </div> <!-- end of box outline -->
      </li>
    </ul>
  </div>
</section> 
<br>
<br>

src/app/views/home/_erb.html.erb
<h2>ERB basics</h2>
<p>
  <%# You'll notice the tags are in tags. It's because otherwise %>
  <%# they will be parsed as code and I want plain text here. %>
  To run ruby code, put it in a tag formatted like this:
  <br>
  <mark><%% app_name() %></mark> -> <% app_name() %>
  <br>
  However, that won't change the HTML sent to the client. In fact, even if
  we tried to write something that would be part of the document like this
  <br>
  <mark><%% 'Hello, world!' %></mark> -> <% 'Hello, world!' %>
  <br>
  Nothing happens still? This is because while rails inputs the return value of 
  a block of code like this into the document, it only does so if we tell
  the language to do so. We do that like this. Add an = to the front of
  the block.
  <br>
  <mark><%%= 'Hello, world!' %></mark> -> <%= 'Hello, world!' %>
  <br>
  And success! However, in doing so, we found something important.
  If you want to run some code like an if around HTML depending on if the 
  user is logged in or not, use <mark><%% if %> ... <%% else %> ... <%% end %></mark>.
  None of these tags will output anything since there's no =, so you
  can do things like this. However, if you do want to output something,
  make sure to use the equal sign at the front, or you'll be confused as
  to why nothing is printing!
  <br>
  Oh, and comments are like this. <mark><%%# Hiya! %></mark>. They will not be
  written to the HTML file sent to the user.
</p>
<h2>Writing good html.erb files</h2>
<p>
  Here's the golden rule of erb: don't process data in the erb file!
  There's nothing to stop you from processing information within the view
  itself, but this is very bad practice for several reasons.
</p>
<p>
  The main reason is simple. MVC. Model, View, Controller. A view should
  NOT be fetching its own information or manipulating models. That's the 
  controller's job. Keeping these tasks seperate will make your view
  files highly readable. Speaking from experience, Software Engineering
  projects can become complex due to (unavoidable, you're learning!)
  inexperience with web development and the MVC model. Doing your best to
  follow those guidelines will help you substancially in the last few
  assignments of the classs.
</p>

src/app/views/home/_filetree.html.erb
<h2>File Structure</h2>
<p>
  The rails file structure is strange. Please be patient. You'll learn it in time.
</p>
<p>
  Note: The following has important sections bolded and underlined. The
  other sections can be largely ignored unless you have some specific need
  for them. <i>Not automatically made</i> means that a brand new rails 
  project will not contain this file. Some things were made to give
  you a starting point for the class.
</p>
<pre>
tcnj-rails-image/app
├── <b><mark>assets (Holds images, CSS, and javascript)</mark></b> 
│   ├── <mark><b>config</b></mark>
│   │   └── <mark><b>manifest.js (how to assemble the things in assets)</b></mark>
│   ├── <mark><b>images (any statically available images)</b></mark>
│   ├── <mark><b>javascripts</b></mark>
│   │   └── <mark><b>application.js (global javascript)</b></mark>
│   └── <mark><b>stylesheets</b></mark>
│       ├── <mark><b>application.scss (global css)</b></mark>
│       └── <mark><b>home.scss (controller specific css [not automatically made])</b></mark>
├── channels
│   └── application_cable
│       ├── README.md
│       ├── channel.rb
│       └── connection.rb
├── <mark><b>controllers (The C of MVC. Handles data manipulation and handling.)</mark></b>
│   ├── <mark><b>application_controller.rb (Superclass of all controllers)</mark></b>
│   ├── concerns
│   └── <mark><b>home_controller.rb (Controller for the home pages [not automatically made])</mark></b>
├── <mark><b>helpers (Any helper methods wanted inside of erb files)</b></mark>
│   ├── <mark><b>application_helper.rb (Superclass of all helpers</mark></b>
│   └── <mark><b>home_helper.rb (Helpers specific to views within the home folder [not automatically made])</mark></b>
├── javascript (this is webpack specific and will probably be ignored)
│   ├── channels
│   │   ├── consumer.js
│   │   └── index.js
│   └── packs
│       └── application.js
├── <mark><b>jobs (Workloads to be run in the background)</mark></b>
│   └── <mark><b>application_job.rb (Superclass of all jobs)</b></mark>
├── mailers
│   └── application_mailer.rb
├── <mark><b>models (The M of MVC, storing and representing information)</mark></b>
│   ├── <mark><b>app_config.rb (A model for strong global settings [not automatically made])</mark></b>
│   ├── <mark><b>application_record.rb (The superclass of all models)</mark></b>
│   ├── concerns
│   └── <mark><b>user.rb (A model representing a website user [not automatically made])</mark></b>
└── <mark><b>views (The V of MVC, defining how information is presented to a user)</mark></b>
    ├── <mark><b>home (Views for the home controller [not automatically made])</mark></b>
    │   ├── _erb.html.erb (A piece of the index page)
    │   ├── _filetree.html.erb (A piece of the index page)
    │   ├── _mvc.html.erb (A piece of the index page)
    │   └── <mark><b>index.html.erb (The webpage you're staring at)</mark></b>
    └── <mark><b>layouts (Special views that contain the common outside of all pages)</mark></b>
        ├── <mark><b>application.html.erb (The content displayed on <i>every</i></mark></b>
        ├── mailer.html.erb
        └── mailer.text.erb
</pre>
</p>

src/app/views/home/_mvc.html.erb
<h2>The MVC Model of web development</h2>
<p>
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/MVC-Process.svg/400px-MVC-Process.svg.png">
</p>
<p>
  <b>Model:</b> data organization<br>
  <b>View:</b> the presentation of information to the user<br>
  <b>Controller:</b> the manipulation and overseeing of information and access to it
</p>
<p>
  These three categories make up the design of practically every application,
  desktop or internet enabled. It's the seperation of these tasks that
  keeps an application easy to maintain, write, and read. Please make sure
  to understand these categories before working with rails. If you don't 
  recall seeing these terms before, check the class slides.
</p>
<p>
  For more information, see <a href="https://www.wikiwand.com/en/Model%E2%80%93view%E2%80%93controller">Wikipedia</a>.
</p>

src/app/views/home/index.html.erb
<!-- 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: index.html.erb
#Description: This is the html landing page. It provides all the information that can be found
on the website. 
#Last modified on: 04-25-2022 */-->

<!--formatting and information for the header -->  


<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- FontAwesome CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<%# <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> %>



<section class="how-it-works bg-white ">
  <div class="image-block-inner">
   <div class="card px-5 my-5 shadow-lg p-3 mb-5 rounded justify-content", style="background-color:  #301934 ">
     <div class="row pb-5 p-3 mb-5 ">
       <div class="text-center text-white col-md-8 mx-auto"> 
        <hr class="divider border text-white border-5"/>
         <h2>The Vision</h2>
         <p>To create an application that allows us to understand the importance of addressing such 
         issues and educates people more on how prevalent domestic violence iss below you will 
         find information about what this application offers</p>
          <hr class="divider border border-5" />
         <p> If you have time please take a quick survey to help us understand more about the user demographics <p>
         <%= link_to 'Survey', new_survey_path, class:"btn btn-outline image-block-inner text-dark", style: "background-color: white" %>
         <hr class="divider border border-5" />
       </div>
     </div>
    <!--formatting and information for the body and information inside it -->
     <div class="row ">
       <div class="row pb-3 justify-content-center" >  

         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 box mb-3 bg-white shadow-lg p-3 mb-5  rounded", style = "margin: 0 20px 0 0px" > 
         <a class="text-dark" href=<%= home_testimonies_path%>>
           <div class="d-flex p-3  align-items-center bg-white justify-content-between ">
             <div class="p-1 ">
               <h3 class="h4 mt-3 ">Real Life Testimonies</h3>
               <p class="mt-3">Learn about domestic violence by reading about real life experiences</p>
             </div>
           </div>
         </div>
        
         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 box mb-3 bg-white shadow-lg p-3 mb-5 rounded", style = "margin: 0 0px 0 20px">
         <a class="text-dark" href=<%= lawquizzes_path%>>
           <div class="d-flex p-3 align-items-center bg-white justify-content-between">
             <div class="p-1">
               <h3 class="h4 mt-3 ">The Domestic Violence History and Laws</h3>
               <p class="mt-3">Learn About Domestic Violence Laws</p>
             </div>
           </div>
         </div>

         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 box mb-3 shadow-lg p-3 mb-5 rounded", style = "margin: 0 20px 0 0px"> 
         <a class="text-dark" href=<%= statsquizzes_path%>>
           <div class="d-flex p-3 align-items-center justify-content-between">
             <div class="p-1">
               <h3 class="h4 mt-3 ">Statistics and Facts</h3>
               <p class="mt-3">Read About Statistics and facts regarding Domestic Violence </p>
             </div>
           </div>
         </div>

         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 box mb-3 bg-white shadow-lg p-3 mb-5 rounded", style = "margin: 0 0px 0 20px">  
         <a class="text-dark" href=<%= helpquizzes_path%>>
           <div class="d-flex p-3 align-items-center bg-white justify-content-between"> 
             <div class="p-1">
               <h3 class="h4 mt-3 ">How can you help? </h3>
               <p class="mt-3">Learn about how you can contirbute to raising awareness? </p>
             </div>
           </div>
         </div>

         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 bg-white box mb-3 shadow-lg p-3 mb-5  rounded", style = "margin: 0 36px 0 0px">
         <a class="text-dark" href=<%= home_DV_path%>>
           <div class="d-flex p-3  align-items-center bg-white justify-content-between">
             <div class="p-1"> 
               <h3 class="h4 mt-3" >Take A Quiz</h3>
               <p class="mt-3">Interact and show how much you've learned by taking quizzes</p>
             </div>
           </div>
         </div>

         <div class="col-md-6 mt-2 mt-md-0 p-2 pl-4 box mb-3 shadow-lg p-3 mb-5  rounded",style = "margin: 0 0px 0 20px">
         <a class="text-dark" href=<%= home_resources_path%>>
           <div class="d-flex p-3  align-items-center justify-content-between bg-white">
             <div class="p-1">
               <h3 class="h4 mt-3 ">Links and Resources</h3>
               <p class="mt-3">Find all the links and resources that were used for this information</p>
             </div>
           </div> 
         </div>
       </div>
     </div>
   </div> 
 </section>

src/app/views/home/resources.html.erb
<!-- 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: resources.html.erb
#Description: This is the html page that has the resources information. 
#Last modified on: 04-25-2022 */-->
<head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content=
        "width=device-width, initial-scale=1, 
        shrink-to-fit=no">
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  
    <title>Bootstrap 4 Shadow</title>
</head>

<!--formatting and information for the text to provide hover effects-->
<section class="news pt-0 bg-white ">
  <div class="image-block-inner">
  <div class="card mt-md-5 my-5 shadow-lg p-3 mb-5 rounded", style="background-color: #301934"> 
    <div class="row ">
    <div class="text-center col-md-8 mx-auto text-white"> 
    <hr class="divider border border-5"/>
    <h2 class="mx-4 my-0 text-center">Links Used & Resources </h2>  <br> 
    <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://www.thehotline.org/?utm_source=google&utm_medium=organic&utm_campaign=domestic_violence" > DOMESTIC VIOLENCE HOTLINE</a></p>
    <hr class="divider border border-5"/> 
    </div></div> 
    <ul class="row d-lg-flex list-unstyled image-block justify-content-center px-lg-0 mx-lg-0">
      <li class="col-lg-10 col-md-6 image-block full-width p-3">
        <div class="image-block-inner", style="background-color: white">
          <a class="mh-100  image-block-inner text-dark">
            <!--<img src="" alt="Picture2" class="img-responsive w-100"></a> -->
          <span class="hp-posts-cat">1. Resources: </span>
          <p class="mt-3 "><a class= "text-dark">
            National Domestic Violence Hotline
            Hours: 24/7. Languages: English, Spanish and 200+ through interpretation service Learn more
            <strong>800-799-7233</strong>  </a></p>   
          <hr class="divider border border-5"/> 
          <a class="mh-100  image-block-inner text-dark">
          <span class="hp-posts-cat">2.The links used for the quizzes and information and additional helpful links:  </span> 
          <p class="mt-3"><a class= "text-dark">
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://freedomandcitizenship.columbia.edu/ipv-history" > Website for information about history</a></p>
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://www.verywellmind.com/how-to-help-a-victim-of-domestic-violence-66533 " > How to help a victim</a></p> 
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href=" https://www.womenslaw.org/laws/pa " > More Domestic Violence laws</a></p>
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://ncadv.org/STATISTICS " > Domestic Violence Statistics</a></p>
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://www.safehorizon.org/get-informed/domestic-violence-statistics-facts/ " > Domestic Violence Facts (1)</a></p>
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href=" https://www.doorwaysva.org/our-work/education-advocacy/the-facts-about-domestic-violence/ " > Domestic Violence Facts (2)</a></p>
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href="https://www.nj.gov/dcf/women/domestic/ " > Domestic Violence information and helpful government link</a></p>
          <hr class="divider border border-5"/>  
          <a class="mh-100  image-block-inner text-dark">
          <span class="hp-posts-cat">3. Donate: </span>   
          <p class="mt-3"><a class= "text-dark"> 
          <p><a class="btn btn-outline image-block-inner text-dark" target="_blank" rel="noopener noreferrer" , style= "background-color: white" href=" https://www.womenagainstabuse.org/donate  " > Donate to help victims of Domestic Violence</a></p>
        </div> <!-- end of box outline --> 
      </li>
    </li>
    </ul>
    <%= link_to 'Back', href= home_DV_path,  class:"btn btn-outline image-block-inner text-dark", style: "background-color: white" %> 
  </div> 
</section> 