src/config/routes.rb
=begin 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: routes.rb
#Description: This file helps define paths by telling the 
rails server how incoming requests are sent to which controller and method
#Last modified on: 03-24-2022
=end 

# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :surveys
  resources :helpquizzes
  resources :lawquizzes
  resources :statsquizzes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller' 

  #added two routes
  root 'home#index'
  get 'home/DV'
  get 'home/testimonies'
  get 'home/resources'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/models/survey.rb
class Survey < ApplicationRecord
end

src/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ] 
  skip_before_action :authenticate_user!

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:answer_1, :answer_2, :answer_3, :answer_4)
    end
end

src/app/helpers/surveys_helper.rb
 
#  Project name: Assignment-2
#  Description: This project implements a quiz functionality
#  Filename: surveys_helper.rb
#  Description: This file holds the questions for the survey 
#  Last modified on: 05/12/2022 

module SurveysHelper 
    def survey_1
        return "What is your age range? " 
    end  
    def survey_2
        return "What is your gender? " 
    end 
    def survey_3
        return "If you were a victim of domestic violence which of the following would you first consider going to for help? " 
    end 
    def survey_4
        return "Have you or anyone you know been a victim of domestic violence?  " 
    end 
end

src/app/views/surveys/_form.html.erb
<!-- 
// Project name: Assignment-2
// Description: This project implements a quiz functionality
// Filename: _form.html.erb
// Description: This file creates the form for a survey submission, includes the survey question and possible answers. 
// Last modified on: 05/12/2022 --> 


<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<section class="news pt-0 bg-white">
  <div class="image-block-inner">
  <div class="card mt-md-5 my-5 shadow-lg p-3 mb-5 rounded", style="background-color: #301934"> 
    <div class="row ">
      <div class="text-center col-md-8 mx-auto text-white"> 
        <hr class="divider border border-5"/>
        <h2 class="mx-4 my-0 text-center"> Survey <br> </h2>
        <hr class="divider border border-5"/> 
        <p> Help us make a difference </p>
        <hr class="divider border border-5"/> 
      </div> </div> <br>
      <div class = "field text-white" >
            <%= survey_1() %> <br>
            <%= form.radio_button(:answer_1, "under 15", required: "required") %> 
            <%= form.label :answer_1, "under 15" %> <br>
            <%= form.radio_button(:answer_1, "15-20") %> 
            <%= form.label :answer_1, "15-20" %><br>
            <%= form.radio_button(:answer_1, "21 or above") %> 
            <%= form.label :answer_1, "21 or above" %> <br> <br>
            <%= survey_2() %> <br>
            <%= form.radio_button(:answer_2, "Male (including transgender men)", required: "required") %> 
            <%= form.label :answer_2, "Male (including transgender men)" %> <br>
            <%= form.radio_button(:answer_2, "Female (including transgender women)", required: "required") %> 
            <%= form.label :answer_2, "Female (including transgender women)" %><br>
            <%= form.radio_button(:answer_2, "Prefer to self describe as non-binary, gender-fluid, agender", required: "required") %> 
            <%= form.label :answer_2, "Prefer to self describe as non-binary, gender-fluid, agender" %> <br> 
             <%= form.radio_button(:answer_2, "none of the above", required: "required") %> 
            <%= form.label :answer_2, "None of the above" %> <br> 
             <%= form.radio_button(:answer_2, "Prefer not to say", required: "required") %> 
            <%= form.label :answer_2, "Prefer not to say" %> <br> <br>
            <%= survey_3() %> <br>
            <%= form.radio_button(:answer_3, "Family member", required: "required") %> 
            <%= form.label :answer_3, "Family member" %> <br>
            <%= form.radio_button(:answer_3, "Friend") %> 
            <%= form.label :answer_3, "Friend" %><br>
            <%= form.radio_button(:answer_3, "Police") %> 
            <%= form.label :answer_3, "Police" %> <br> <br> 
            <%= survey_4() %> <br>
            <%= form.radio_button(:answer_4, "yes") %> 
            <%= form.label :answer_4, "yes" %> <br>
            <%= form.radio_button(:answer_4, "no") %> 
            <%= form.label :answer_4, "no" %><br><br>
  <div class="actions">
    <%= form.submit "submit survey", class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"  %> <br><br>
  </div> 
<% end %>

src/app/views/surveys/edit.html.erb
<!-- 
// Project name: Assignment-2
// Description: This project implements a quiz functionality
// Filename: edit.html.erb
// Description: This handles the edit page, and renders from 
// Last modified on: 05/12/2022 --> 

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey, class:"btn btn-outline image-block-inner text-dark", style: "background-color: white" %>
<%= link_to 'Back', home_DV_path, class:"btn btn-outline image-block-inner text-dark", style: "background-color: white" %> 

src/app/views/surveys/index.html.erb
<!-- 
// Project name: Assignment-2
// Description: This project implements a quiz functionality
// Filename: index.html.erb
// Description: This is a table display of all the answers for the survey, only admins see this page. 
// Last modified on: 05/12/2022 --> 

<%# table to hold the responses  %>
<h1>All Survey Responses</h1>
<div class = "container center">
<table class = "table">
  <thead>
    <tr>
      <th scope="col">Age</th> 
      <th scope="col">Gender</th>
      <th scope="col">Peferred contact</th>
      <th scope="col">Victim or knows a victim of DV?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> 
  <%# get all responses for each survey with an option to delete and show the results %>
    <% @surveys.each do |survey| %>
      <tr style="white-space:nowrap">
        <td><%= survey.answer_1 %></td> 
        <td><%= survey.answer_2 %></td>
        <td><%= survey.answer_3 %></td>
        <td><%= survey.answer_4 %></td>
        <td><%= link_to 'Show', survey,  class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"  %></td>
        <td><%= link_to 'Delete', survey, method: :delete, data: { confirm: 'Are you sure?' },  class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

src/app/views/surveys/new.html.erb
<!-- 
// Project name: Assignment-2
// Description: This project implements a quiz functionality
// Filename: new.html.erb
// Description: This file renders a new survey form. 
// Last modified on: 05/12/2022 --> 
<%= render 'form', survey: @survey %>

src/app/views/surveys/show.html.erb
<!-- 
// Project name: Assignment-2
// Description: This project implements a quiz functionality
// Filename: show.html.erb
// Description: This file a user the answers they picked. 
// Last modified on: 05/12/2022 --> 


<br> 
<%# diplay the table answers that the user just picked with the option of editing them %>
<section class="news pt-0 bg-white">
  <div class="image-block-inner">
  <div class="card mt-md-5 my-5 shadow-lg p-3 mb-5 rounded", style="background-color: #301934"> 
    <div class="row ">
      <div class="col-md-8 mx-auto text-white"> 
        <hr class="divider border border-5"/>
          <p>
            <strong><%=survey_1()%></strong>
            <%= @survey.answer_1 %>
          </p> 
          <p>
            <strong><%=survey_2()%></strong>
            <%= @survey.answer_2 %>
          </p>

          <p>
            <strong><%=survey_3()%></strong>
            <%= @survey.answer_3 %>
          </p>

          <p>
            <strong><%=survey_4()%></strong>
            <%= @survey.answer_4 %>
          </p> <hr class="divider border border-5"/>
          </div></div></div></div>

          <div> 
          <%# if user is signed in display only the back option %>
            <% if user_signed_in? %>
                <%= link_to 'Back', surveys_path ,  class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"  %> 
            <% else %>
              <%= link_to 'Edit', edit_survey_path(@survey), class:"btn btn-outline image-block-inner text-dark", style: "background-color: white" %> |
              <%= link_to 'Back', home_DV_path, class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"%> <br>
            <% end %>
          </div> 