src/config/routes.rb
=begin 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: routes.rb
#Description: This file helps define paths by telling the 
rails server how incoming requests are sent to which controller and method
#Last modified on: 03-24-2022
=end 

# frozen_string_literal: true
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :surveys
  resources :helpquizzes
  resources :lawquizzes
  resources :statsquizzes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller' 

  #added two routes
  root 'home#index'
  get 'home/DV'
  get 'home/testimonies'
  get 'home/resources'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/views/layouts/application.html.erb
<!-- 
#Project name: Assignment-2  
#Description: Creating a domestic violence awareness 
web application with an interactive quiz
#Filename: application.html.erb
#Description: This code has the bootstrap information and the nav bar creation and their defined paths. 
#Last modified on: 05-12-2022 */-->
<!DOCTYPE html>
<html>
<head> 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> <%= app_name %></title> 
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
  <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
  
 
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% # added a css file to make the about page look nice %>
     <%= stylesheet_link_tag 'DV.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%# Bootstrap css %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <%# Bootstrap js & dependencies %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <%# Navigation Bar %>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top text-white" > 
      <br> <br><a class="navbar-brand" , href="/">FightDomesticViolence</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="/home/DV">Learn More</a>
          </li>
           <li class="nav-item ">
            <%= link_to 'Survey    ', new_survey_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to 'Survey Responses',  surveys_path, class:"nav-link" %>
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <%# If user, show account, else sign in %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
                Account
              </a>
              <%# Change to rails "link_to" for the actual links when implementing %>
              <%# Make sure to include the css class as shown in the login example %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%# The rails administration panel link %>
                <% if Rails.env.development? %><%= link_to 'Rails Admin', rails_admin_path, class: "dropdown-item" %><% end %>
                <div class="dropdown-divider"></div>
                <%# Devise requires that the logout command be sent using the 'delete' HTTP verb (method) %>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item", style = "margin: 0 20px 0 0px">
              <%= button_to "Login", new_user_session_path, class:"btn btn-outline image-block-inner text-dark", style: "background-color: white"  %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <div class="container">
    <br>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body> <br><br><br>
</html>  